name: snapcraft-parts
version: 0
summary: Cloud part for apps using the Liri Platform snap
description: |
  Helper for Liri Apps depending on the Liri Platform snap.
  Includes a specific launcher and Snapcraft configuration
  to deduplicate build configurations.
parts:
  liri-platform-0-9:
    plugin: dump
    source: src
    install: |
      mkdir $SNAPCRAFT_PART_INSTALL/liri-platform
      mkdir $SNAPCRAFT_PART_INSTALL/meta
      echo 'liri-platform-0-9' >> $SNAPCRAFT_PART_INSTALL/meta/platform
      mkdir $SNAPCRAFT_PART_INSTALL/bin
      echo '[Paths]' >> $SNAPCRAFT_PART_INSTALL/bin/qt.conf
      echo 'Prefix = /snap/liri-platform-0-9/current/lib/qt5' >> $SNAPCRAFT_PART_INSTALL/bin/qt.conf
    organize:
      launcher.sh: bin/liri-app-launch
    stage:
      - meta/
      - liri-platform/
      - bin/liri-app-launch
      - bin/qt.conf
  liri-platform-ext-qt-xcb-software:
    plugin: dump
    source: src
    organize:
      ext/qt-xcb-software.sh: bin/ext/qt-xcb-software.sh
    stage:
      - bin/ext/qt-xcb-software.sh
  liri-platform-ext-snap-classic:
    plugin: dump
    source: src
    organize:
      ext/snap-classic.sh: bin/ext/snap-classic.sh
    stage:
      - bin/ext/snap-classic.sh
